include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disabled - too noisy for now
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_locals: false
    unnecessary_brace_in_string_interps: false
    
    # Keep these enabled
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    todo: ignore
    unnecessary_import: ignore
    unrelated_type_equality_checks: ignore
    avoid_print: ignore
